### ISSUE TITLE
cordova view resolution problem

### ISSUE THREAD

**Issue by geniusq1981** [apache/cordova-lib#718] opened 2018-11-07 08:17 UTC
How to change cordovawebview resolution？

Case is：
I make a web app on android TV by cordova.
The TV device resolution is 1920x1080.
but when I run the app , the window.innerwidth/innerheight is 960x540 though it is fullscreen also.
While the html page is designed with 1920*1080 , so it was shown partly.
I find nothing useful about this from the cordova offical guideline.
 
Hope some help from you.

**Comment by jameelio** [comment] 2018-12-04 08:20
Hi @geniusq1981 I am experiencing the same issue at the moment,while developing in cordova using inappbrowser. I would like to know if you got a way around this issue.
Kind Regards

**Comment by basvanmeurs** [comment] 2019-01-11 11:15
Same here. Actually I built my own Activity (without cordova) and the scaling worked fine. I couldn’t really find the cause so far but noticed that the initial precision was set to 0 by cordova (???). When I manually reset the precision to 1 the scaling was better but still not correct.

**Comment by getDOKI** [comment] 2019-01-20 21:52
Any fix for this issue?

**Comment by rokobuljan** [comment] 2019-01-21 22:43
Also having the exact same issue. By removing `meta` for viewport, and directly loading the page on a mobile device (1080x1920 in my case) the website shows exactly as expected - in that "resolution". But, wrapped by WebView it appears scaled... I have no plans to use CSS scale to fix this issue. Any solution to this?

**Comment by brodybits** [comment] 2019-01-22 00:20
Please raise Android-specific issue in: <https://github.com/apache/cordova-android/issues>

I cannot promise when a maintainer would get a chance to look at this one.

A couple more ideas:
- try <xhttps://github.com/ionic-team/cordova-plugin-ionic-webview>
- try Capacitor framework

**Comment by tscislo** [comment] 2019-09-03 21:48
Was anyone able to solve this using just Cordova?

**Comment by onelsonic** [comment] 2019-11-21 10:17
same issues here I moved it to https://github.com/apache/cordova-android/issues

**Comment by raphinesse** [comment] 2019-11-21 10:34
Closing in favor of apache/cordova-android#870

**Closed by raphinesse** 2019-11-21 10:34 UTC

**Comment by jaydge** [comment] 2020-03-03 21:35
FYI, this is happening on iOS inAppBrowser also.

**Comment by brodybits** [comment] 2020-03-03 21:49
Please report any plugin problems on the appropriate plugin. We really have no extra resources to support closed issues. Thanks.
