### ISSUE TITLE
Ionic 2 build process output steps description is encrypted

### ISSUE THREAD

**Issue by ShayShaked** [apache/cordova-lib#793] opened 2019-08-10 18:45 UTC
Hi,
For a while now we have encounter a problem while running ionic build android.
Previously, the steps of the build process showed exactly what phase he was in.
Now, the steps are encrypted/Hexa.

![Encrypted build](https://user-images.githubusercontent.com/24415207/62825627-bd3fe000-bbb7-11e9-8de3-ea0a2326c2a0.png)

instead of:

![regular build](https://user-images.githubusercontent.com/24415207/62825675-64bd1280-bbb8-11e9-9258-c41adc2f36f9.png)

For some reason the output is encrypted, and run for hours or getting stuck without ending. build goes forever.

Additionally, our network is behind a proxy server.

ionic Info:

ordova CLI: 8.1.1 (cordova-lib@8.1.0)
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.8.0
Xcode version: Not installed

Any suggetions?

**Comment by cklam** [comment] 2019-08-11 14:45
Great 


Sent from Yahoo Mail for iPhone


On Saturday, August 10, 2019, 11:45 AM, ShayShaked <notifications@github.com> wrote:


Hi,
For a while now we have encounter a problem while running ionic build android.
Previously, the steps of the build process showed exactly what phase he was in.
Now, the steps are encrypted/Hexa.



For some reason the output is encrypted, and run for hours or getting stuck without ending. build goes forever.

Additionally, our network is behind a proxy server.

ionic Info:

ordova CLI: 8.1.1 (cordova-lib@8.1.0)
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.8.0
Xcode version: Not installed

Any suggetions?

**Comment by raphinesse** [comment] 2019-11-21 11:26
I have never seen this behavior. Can you [Create a Minimal Reproduction Repository or Sample](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md) please?

**Comment by brodybits** [comment] 2020-01-01 18:26
Closing due to lack of information.

**Closed by brodybits** 2020-01-01 18:26 UTC
Labels: info-needed
